# Generated by Django 5.0.1 on 2025-01-22 18:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_client_hirerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hirerequest',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='hirerequest',
            name='client_name',
        ),
        migrations.AddField(
            model_name='hirerequest',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.client'),
        ),
        migrations.AddField(
            model_name='hirerequest',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hirerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
migrations.AddField(
    model_name='hirerequest',
    name='talent',
    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.talent'),
),

    ]
