# Generated by Django 5.0.1 on 2025-01-22 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_remove_hirerequest_client_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hirerequest',
            old_name='date_sent',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.client'),
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
